name: Submodule Sync

on:
  push:
    branches:
      - sa/test  # Change to the branch where you want updates to trigger

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the submodule repository
        uses: actions/checkout@v4

      - name: Get latest commit hash
        id: submodule_commit
        run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Clone the main repository
        id: clone_repo
        run: |
          git clone --recurse-submodules https://x-access-token:${{ secrets.SUBMODULE_TOKEN }}@github.com/kiriminaja/kaj-sandbox-web.git main-repo
          cd main-repo
          git config user.name "yanuaraditia"
          git config user.email "yanuaraditia@outlook.com"

      - name: Update submodule reference
        id: push_repo
        run: |
          cd main-repo
          git submodule update --force --remote --recursive
          git add content
          git commit -m "Update submodule to latest commit: ${{ env.SHA }}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.SUBMODULE_TOKEN }}@github.com/kiriminaja/kaj-sandbox-web.git
          git push origin HEAD:main